### ISSUE TITLE
Open & Link Merchant Account or Fiscal Host

### ISSUE THREAD

**Issue by senakim18** [civictechstructure/admin-donation-infrastructure#2]
### Overview
To accept donations or direct sponsorships without a subscription offer with Github Sponsors, CTS needs a merchant account linked to its sponsored organization status. CTS also needs a 3rd party payment service provider (e.g., Stripe) to accept donations outside of Github Sponsors.

### Action Items

- [x] Open merchant account
- [x] Choose payment processing service

### Merchant Account Options

- [x] First Citizens Bank

### Payment Processing Service Options

- Donorbox
  * Requires a separate merchant account + payment processor (they said PayPal or Stripe) to link to Donorbox
  * $0 monthly plan: 1.75% platform fee for donation forms, hosted pages, quick donate. 2.95% platform fee for events, memberships, supporters
  * Didn't give specific customers to talk to but provided a link to [case studies](https://donorbox.org/case-studies)
  * They gave a list of "[best banks for nonprofits](https://donorbox.org/nonprofit-blog/nonprofit-banking#8)": PNC, US Bank, Wells Fargo, M&T Bank
       * need to look into these separately, if interested 
   
- Stripe
  * No monthly fees
  * merchant account + payment processing
  * 2.9% + 30c per successful card charge, more details [here](https://stripe.com/pricing)

- Square
  * No monthly fees
  * merchant account + payment processing
  * [Other processing fees](https://squareup.com/us/en/pricing) vary: 2.6% + 10c per in-person card transactions, key in card: 3.5% + 15¢ per transaction.

### Resources/Instructions
GitHub Sponsors supports these fiscal hosts. They don't have recommendations for merchant accounts.

- [Open Source Collective](https://oscollective.org/): Fees = 10% of incoming funds, plus payment processor fees
- [NumFOCUS](http://www.numfocus.org/): [Application process](https://numfocus.org/projects-overview) (focus on research, software packages)
- [Open Collective Europe](https://opencollective.com/europe): [Application process](https://opencollective.com/europe/apply). Fees range from 6% + credit card fees (2.9% + €0.25 for non-European cards, 8% for most projects, 10% for tax deductible donations from US 501(c)(3) foundations 
- [Software Underground](https://softwareunderground.org/): Geology focus
- [Software Freedom Conservancy](https://sfconservancy.org/): [Application process](https://sfconservancy.org/projects/apply/)

[Github Sponsors Additional Terms](https://docs.github.com/en/site-policy/github-terms/github-sponsors-additional-terms)
[Linking a fiscal host to Github Sponsors](https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/using-a-fiscal-host-to-receive-github-sponsors-payouts)

**Comment by senakim18** [comment]
@lizoh12
- [x] contact Github support to ask about sponsor buttons to direct funds to specific campaigns
- [x] contact Donorbox to ask for customer feedback + recommendation of merchant account providers

**Comment by lizoh12** [comment]
> @lizoh12
> 
> * [x]  contact Github support to ask about sponsor buttons to direct funds to specific campaigns
> * [x]  contact Donorbox to ask for customer feedback + recommendation of merchant account providers

Waiting for responses from Stripe, Github, and Donorbox inquiries.

**Comment by lizoh12** [comment]
Helcum doesn't seem to provide what is needed - It doesn't have an option to designate to specific campaigns (would need to setup multiple accounts). I found Payment Depot through nerdwallet but we can't separate out campaigns either. 

Square can do everything we need - it's a merchant account + processing, can create separate buttons for separate campaigns (couple different options to do this). They take bank transfers, but use an invoicing process that once received takes 3-5 business days. International cards are accepted. They didn't have a formal partnership/integration with GitHub, so I sent a support ticket to Github asking. 

[Square pricing](https://squareup.com/us/en/pricing): 2.9% + 30c for transaction & processing fees. No monthly charges.

**Comment by lizoh12** [comment]
> Choose between fiscal host, bank account, or Stripe account

Clarification: Github only uses Stripe to process & transfer the payments, we'd still need an individual or merchant account, or fiscal host. Updated text in Issue.

**Comment by ExperimentsInHonesty** [comment]
# Profile details
### Short bio (250 characters)
This appears wherever your sponsorship is shared (for example, in social cards and [github.com/sponsors](https://github.com/sponsors) if you opt-in to be featured).

> Support civictechstructure's open source work

### Introduction 
Your introduction is the main focus that appears on the civictechstructure GitHub Sponsors profile. It's a great opportunity to help potential sponsors learn more about you, your work, and why their sponsorship is important to you.

> Don’t forget to delete this placeholder text 🙃
> 
> Here are some ideas of what you can tell your potential sponsors:
> - [ ] Who are you, and where are you from?
> - [ ] What are you working on?
> - [ ] Why is their sponsorship important? How will you use the funds?
> 
> Hint: You can include images and emojis in your bio!


### Meet the team (optional)
Highlight members of the civictechstructure organization on your GitHub Sponsors profile. The first 8 users will be shown on load while the remaining users will be shown in a toggleable section below.

### Featured work (optional)
Select public repositories to showcase on your GitHub Sponsors profile


### Optional: Opt-in to get featured on [github.com/sponsors](https://github.com/sponsors)
If we choose to feature you, we'll show your avatar and short bio on the Sponsors page—another way for potential sponsors to find you!

**Comment by ExperimentsInHonesty** [comment]
stripe needs a description for the credit card statement.  there is a short version and a long version. we want to use a domain name.  

- [ ]  figure out how many characters the domain name can be.

**Comment by senakim18** [comment]
Hi @ExperimentsInHonesty , Stripe needs you to verify your full SSN (currently it says that Payouts and Charges are restricted). I couldn't figure out how to add the Google voice number as the new number until that's resolved.

**Comment by senakim18** [comment]
I tried logging into Donorbox via Stripe, but it said "Account not found." I'm not sure what I'm doing wrong :( 


![Screenshot 2023-07-26 at 10 17 22 PM](https://github.com/civictechstructure/admin-donation-infrastructure/assets/127809340/3627e794-d3f4-4af7-9dba-7a0b6782b874)
![Screenshot 2023-07-26 at 10 17 32 PM](https://github.com/civictechstructure/admin-donation-infrastructure/assets/127809340/2d2c0afe-1e16-4899-b5ae-b9d6589a7b03)
